# Generated by Django 2.0.4 on 2018-11-16 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, max_length=100, null=True, verbose_name='学校')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='公司')),
                ('profession', models.CharField(blank=True, max_length=100, null=True, verbose_name='职业')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='住址')),
                ('aboutme', models.TextField(blank=True, null=True, verbose_name='自我介绍')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='头像')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='手机号码')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
